<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DellLaptop" failures="2" tests="5" name="Login - Test cases" time="27.617" errors="0" timestamp="2022-02-13T13:37:36 EST">
  <testcase classname="com.salesforcenew.testCases.LoginTest" name="loginTest" time="3.436"/>
  <testcase classname="com.salesforcenew.testCases.LoginTest" name="loginErrorMessage" time="0.473">
    <failure type="java.lang.AssertionError" message="expected [Please enter your password.] but found []">
      <![CDATA[java.lang.AssertionError: expected [Please enter your password.] but found []
at com.salesforcenew.testCases.LoginTest.loginErrorMessage(LoginTest.java:66)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- loginErrorMessage -->
  <testcase classname="com.salesforcenew.testCases.LoginTest" name="rememberMe" time="7.57">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.salesforcenew.testCases.LoginTest.rememberMe(LoginTest.java:100)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- rememberMe -->
  <testcase classname="com.salesforcenew.testCases.LoginTest" name="forgotPassword" time="0.227"/>
  <testcase classname="com.salesforcenew.testCases.LoginTest" name="validateloginErrorMessage" time="0.301"/>
</testsuite> <!-- Login - Test cases -->
